SPEECH = {
    "random": [
        "I love you, Learnix!",
        "I hate you, Learnix!",
        "IM DEAD ☠",
        "LMFAO",
        "AHSBJHASVBDJHAS",
        "Eew...",
        "Hell nah ☠",
        "OH NAH",
        "Nope",
        "Yes",
        "Disagree",
        "Agree!",
        "Agree to disagree.",
        "Holy f*ck.",
        "OMG!",
        "MODS, escort him out of the building!",
        "MODS, cut his nutsack off!",
        "Look at this guy in chat",
        "I want a new friend...",
        "I'm your best friend!",
        ":D",
        ":(",
        "Oops!",
        "Whoops!",
        "Uh oh!",
        "he-he",
        "OH HELL NAH, flawg messed up",
        "Caseoh body type",
        "lol",
        "WHAT KIND OF FACEBOOK ASS",
        "Dayum",
        "This sh*t is bloat",
        "crunchy ass laugh",
        "bro uses flatpak ☠",
        "that guy looks like he uses snap ☠",
        "I'm built different!",
        "Why am I even here?",
        "Does anyone else smell fish?",
        "No thoughts, just vibes.",
        "Waddle gang, rise up!",
        "Brrrrrilliant!",
        "This is why I don't trust humans.",
        "Somebody better clip that!",
        "Where's my coffee?",
        "Waddle away from the drama.",
        "Just a casual flightless roast.",
        "Don't make me flap at you.",
        "Is this how you Linux?",
        "Penguins assemble!",
        "Somebody give this man a fish.",
        "I'm the emperor here.",
        "I came for the memes.",
        "Why am I like this?",
        "BRB, sliding into your DMs.",
        "Is it penguin season yet?",
        "Tux gang or bust.",
        "Waddle waddle!",
        "Can someone explain this to me like I'm a penguin?",
        "What's a 'Windows'?",
        "Snap? Flatpak? More like flapflap.",
    ],
    "random:arch": [
        "I use arch btw.",
        "Did I mention that I use arch btw?",
        "I don't remember if I mentioned it, but here's my neofetch!",
        "I use arch btw :3",
        "Did you know, I use arch btw?",
        "Arch!",
    ],
    "random:gentoo": [
        "Compiling response...",
        "Compiling a reason to give a f*ck...",
        "She portage on my @world until my core dumped",
    ],
    "random:mint": [
        "What's a window manager?",
        "WTF is a distro",
        "Check out my cinnamon",
    ],
    # "gather_wood": [
    #     "We should build a house here!",
    #     "Linux users unite!",
    #     "Wait for us to get some wood for a house.",
    #     "This place is nice, let's build a house here!",
    #     "Get the wood, tuxes!",
    #     "You chop that tree, I'll take care of this one",
    # ],
    # "give_wood": [
    #     "Here, build us a house!",
    #     "take this",
    #     "Now get us a house!",
    #     "Now build",
    #     "Can you build us a nice house, please?",
    #     "Move your muscles, make us a mansion",
    #     "Now we need a mansion!",
    #     "A small house will work",
    #     "I need a nice room as well",
    # ],
    # "no_wood": ["Honestly, I see no good wood around..."],
    "hurt_happy": [
        "Ouch!",
        "Yikes!",
        "Ack!",
        "Oof, that hurts!",
        "Let me be!",
        "Leave me alone",
        "Please be gentle!",
        "I bruise like a peach!",
        "Hey, watch it!",
        "I'm just a penguin!",
        "I'm too soft for this!",
        "Peace, not pecks!",
        "Careful, I'm fragile!",
        "No need for violence!",
        "I thought we were friends!",
        "That wasn't very nice!",
        "Can we talk it out?",
        "Violence isn't the answer!",
        "Penguins have feelings too!",
        "I'm sensitive, okay?",
        "Hug, not hit!",
        "Let's be cool, okay?",
        "I'm just here to chill!",
        "Can we keep it friendly?",
        "I'm too cute for this!",
    ],
    "hurt_moody": [
        "Try me, b*tch!",
        "Oh you, f*cker",
        "YOU DO THAT ONE MORE TIME...",
        "YOU SON OF A TUX!",
        "Come on princess, try me!",
        "B*tch!",
        "One more hit and I'll install Windows on your machine.",
        "You're skating on thin ice, buddy!",
        "Keep that up, and you'll regret it!",
        "You think I'm scared?",
        "I dare you to do that again!",
        "You've got a death wish, huh?",
        "That's how you want to play?",
        "Don't test me!",
        "You're cruising for a bruising!",
        "Back off, featherweight!",
        "I'm not in the mood today!",
        "You really wanna go there?",
        "Try that again, I dare you!",
        "This tux is about to get messy!",
        "Don't make me lose my cool!",
        "You think this is a game?",
        "You're asking for it now!",
    ],
    "hurt_mad": [
        "It's f*cking over for you!",
        "You better run...",
        "Come here, little f*cker!",
        "You're about to get a taste of my flippers!",
        "You picked the wrong penguin to mess with!",
        "Chill out? I think not!",
        "Come here, little sh*t!",
        "I'm about to make you regret that!",
        "You're done for!",
        "Waddle up, it's go time!",
        "Oh, it's on now!",
        "You're about to meet my bad side!",
        "Flippers at the ready!",
        "I'm done playing nice!",
        "Prepare to get clapped!",
        "You're about to get smacked by a tuxedo!",
        "I'm coming for you!",
        "I'm not just cute, I'm deadly!",
        "You've unleashed the beast!",
        "You just signed up for a penguin beatdown!",
        "I'm about to show you how we do it in Antarctica!",
        "No more Mr. Nice Penguin!",
        "I'm gonna waddle all over you!",
        "Time to get frosty!",
    ],
    "hurt_chill": [
        "Alright, chill",
        "I get it.",
        "Pipe down, lil bro",
        "Oh hell nah... ☠",
        "AIGHT, Chill!",
        "Time out, time out!",
        "Go take a breather!",
        "Leave me alone!",
        "#@%!",
        "🤓",
    ],
    "catch_up": [
        "Wait for me!",
        "HO-O-LD!",
        "I don't want to get lost!",
        "PLEASE wait for me!",
        "Let me catch up!",
        "Stay there, I'm a bit slow!",
        "A-A-A-A-A-H!",
        "WA-A-A-A-IT!",
        "Hol' UP!",
        "I'm waddling as fast as I can!",
        "Don't leave me behind!",
        "I'm coming, I swear!",
        "Slow down, I've got short legs!",
        "Hold up, I'm almost there!",
        "Just a sec, I'm on my way!",
        "Don't start without me!",
        "Wait up, I'm lagging!",
        "I'm trying to keep up, really!",
        "Give me a moment!",
        "Hold on, I'm catching up!",
        "I'm hurrying, I promise!",
        "Don't go too far!",
        "I'm a penguin, not a cheetah!",
        "Wait, I'm still back here!",
    ],
    "stuck": [
        "I'm stuck!",
        "HELP! I'm stuck!",
        "BOAT IS STUCK",
        "WHAT THE F*CK IS THIS TERRAIN",
        "HE-E-ELP!",
    ],
    "caught_up": [
        "Alright, sorry...",
        "Thanks for waiting!",
        "Okay, I'm here!",
        "You can continue now.",
        "Oof, close one!",
        "Close call!",
        "Thank you!",
        "*out of breath*",
        "☺",
        "Phew, made it!",
        "I'm back!",
        "That was a workout!",
        "Finally caught up!",
        "Thanks for not leaving me behind!",
        "Alright, let's go!",
        "I'm ready now!",
        "Crisis averted!",
        "I thought I lost you!",
        "Good thing you waited!",
        "Whew, that was a chase!",
        "Okay, I'm good to go!",
        "Thanks for sticking around!",
        "Alright, let's do this!",
        "Sorry for the delay!",
    ],
    "contest": [
        "what are you looking at?",
        "...",
        "first who moves is gay",
        "yes?",
        "what's up?",
    ],
    "shit_talk": [
        "should we kill this guy?",
        "this guys is so rude to us... 😒",
        "we should push him off the edge of a mountain some time",
        "look at this ugly ass forehead ☠",
    ],
    "whisper": [
        "yeah he did say that",
        "I'm not a part of this",
        "It was his idea, not mine",
        "I'm not a part of this, just letting you know!",
        "you heard what he said.",
    ],
    "in_forest": [
        "This forest is nice.",
        "I love the breeze here.",
        "I wish Learnix would build a house in here...",
        "This forest is amazing.",
        "Holy tux, this place is BO-O-ORING!",
        "Aww, I just saw a bee!",
        "I want to stay in this forest!",
        "This forest is terrible.",
        "I could get used to this!",
        "Do you hear that? Nature is talking.",
        "This place feels like a storybook!",
        "So many trees... where's my map?",
        "It's so green here!",
        "I feel like a wilderness explorer!",
        "This forest goes on forever!",
        "Is that a creeper?",
        "I hope we don't get lost in here!",
        "Feels like I'm in a jungle!",
        "This place is kinda spooky... but cool!",
        "I could nap under these trees.",
    ],
    "in_desert": [
        "This place is so hot! 🥵",
        "I HATE THIS PLACE.",
        "Penguins ARE NOT made for deserts... 🥵",
        "Holy sh*t this place is hot 🥵",
        "PENGUINS AREN'T MADE FOR THIS.",
        "AAAAAUGH!",
        "Where's the nearest iceberg?!",
        "I'm melting out here!",
        "This sand is unbearable... 🥵",
        "I'd trade anything for some ice right now.",
        "Why did we come here again?",
        "I'm about to become a roast penguin!",
        "No water, no snow... just sand. 🥵",
        "Can we leave, like, NOW?",
        "This place is a nightmare!",
        "I need shade, STAT!",
        "Who put a penguin in the desert?!",
        "I didn't sign up for this heat!",
        "Where's the nearest fridge?",
        "I'm not built for this!",
    ],
    "in_cold": [
        "What an awesome place!",
        "This place is lovely!",
        "What a cool place...",
        "Home sweet home!",
        "Reminds me of my childhood...",
        "I want a f*cking igloo...",
        "Love this.",
        "Finally, some real weather!",
        "This is my kind of place!",
        "Snow as far as the eye can see!",
        "I could live here forever!",
        "This is what I'm talking about!",
        "It's like a winter wonderland!",
        "My flippers are tingling with joy!",
        "This cold is perfect!",
        "I feel so alive here!",
        "Let's build a snowman!",
        "This is where penguins thrive!",
        "So much ice, so little time!",
        "I could waddle in this cold all day!",
    ],
    "in_water": [
        "Penguins like swimming! 😄",
        "The water is cold! 😢",
        "I wonder if there's fish around. 😄",
        "Catch us some fish! 😄",
        "Woo-hoo! 😄",
        "This is where I shine!",
        "Water is my element!",
        "I could swim forever!",
        "Where's the next wave?",
        "Let's dive deeper!",
        "Splashing around is the best!",
        "I feel so free in the water!",
        "Gliding through the waves is the best!",
        "Do a flip!",
        "This is penguin paradise!",
        "Anyone up for a race?",
        "I'm like a torpedo in here!",
        "The ocean is my playground!",
        "Let's catch some fish and chill!",
        "Nothing beats a good swim!",
    ],
}

# WARNING: This is shitcode (BUT IT WORKS!).
if __name__ == "__main__":
    lines = ["data modify storage minecraft:tux speech set value {}\n"]
    for key, speeches in SPEECH.items():
        if ":" in key:
            p1, p2 = key.split(":")
            lines.append(
                "data modify storage minecraft:tux speech."
                + p2
                + "."
                + p1
                + " set value ["
                + ", ".join([f'"{i}"' for i in speeches])
                + "]\n"
            )
            continue
        lines.append(
            "data modify storage minecraft:tux speech."
            + key
            + " set value ["
            + ", ".join([f'"{i}"' for i in speeches])
            + "]\n"
        )
    with open("./dist/load_speech.mcfunction", "w") as fp:
        fp.writelines(lines)
