# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
playsound minecraft:entity.player.attack.crit master @a ~ ~ ~ 1 1 0
execute as @n[type=#tux:can_attack,distance=..5] run damage @s 3 minecraft:player_attack by @n[type=minecraft:wandering_trader]
particle spit ^ ^1.2 ^0.8 0.1 0.1 0.1 0.1 10 normal @a
execute at @n[type=#tux:can_attack,distance=..5] run summon wind_charge ~ ~ ~ {Motion:[0.0d, -0.5d, 0.0d]}