# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
playsound minecraft:entity.panda.sneeze master @a ~ ~ ~ 1 1 0
particle spit ^ ^1.2 ^0.8 0.1 0.1 0.1 0.1 4 normal @a