# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.animation_model_idle.frame dummy
scoreboard objectives add aj.animation_model_walk.frame dummy
scoreboard objectives add aj.animation_model_run.frame dummy
scoreboard objectives add aj.animation_model_attack_combo.frame dummy
execute as @e[type=item_display,tag=aj.tux.root] unless score @s aj.is_rig_loaded matches 1 at @s run function animated_java:tux/root/on_load