# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.tux.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'tux', 'function_path': 'animated_java:tux/variants/default/apply'}
execute on passengers if entity @s[tag=aj.tux.bone.head] run function animated_java:tux/variants/default/zzz/0
execute on passengers if entity @s[tag=aj.tux.bone.left_wing] run function animated_java:tux/variants/default/zzz/1
execute on passengers if entity @s[tag=aj.tux.bone.right_wing] run function animated_java:tux/variants/default/zzz/2
execute on passengers if entity @s[tag=aj.tux.bone.body] run function animated_java:tux/variants/default/zzz/3