# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.tux.root] run return 0
execute on passengers if entity @s[tag=aj.tux.data] unless data entity @s {data:{rigHash: '37a7aba1cd9602bcd268f9746b93e3c67f5c13da066a923706758bacce3a52a8'}} on vehicle run function animated_java:tux/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1