# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:tux/animations/animation_model_idle/zzz/apply_frame {frame: 40}
scoreboard players add @s aj.animation_model_idle.frame 1