# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.tux.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'tux', 'function_path': 'animated_java:tux/animations/look_around/play'}
tag @s add aj.tux.animation.look_around.playing
scoreboard players set @s aj.look_around.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:tux/animations/look_around/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only