# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:tux/animations/animation_model_run/zzz/apply_frame {frame: 12}
scoreboard players add @s aj.animation_model_run.frame 1