# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.tux.root] run return 0
execute on passengers if entity @s[tag=aj.tux.data] unless data entity @s {data:{rigHash: 'c93d7050c390686f058c14f43d5c875cb87dec237d43dd20aa30e13673e54f4d'}} on vehicle run function animated_java:tux/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1