# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.tux.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
function #animated_java:tux/as_root/pre_tick
execute if entity @s[tag=aj.tux.animation.idle.playing] run function animated_java:tux/animations/idle/zzz/on_tick
execute if entity @s[tag=aj.tux.animation.walk.playing] run function animated_java:tux/animations/walk/zzz/on_tick
execute if entity @s[tag=aj.tux.animation.run.playing] run function animated_java:tux/animations/run/zzz/on_tick
execute if entity @s[tag=aj.tux.animation.attack_combo.playing] run function animated_java:tux/animations/attack_combo/zzz/on_tick
execute if entity @s[tag=aj.tux.animation.throw.playing] run function animated_java:tux/animations/throw/zzz/on_tick
execute if entity @s[tag=aj.tux.animation.look_around.playing] run function animated_java:tux/animations/look_around/zzz/on_tick
execute if entity @s[tag=aj.tux.animation.sneeze.playing] run function animated_java:tux/animations/sneeze/zzz/on_tick
execute if entity @s[tag=aj.tux.animation.swim.playing] run function animated_java:tux/animations/swim/zzz/on_tick
execute on passengers if entity @s[tag=aj.tux.data] run function animated_java:tux/root/zzz/1
execute at @s on passengers run tp @s ~ ~ ~ ~ ~
function tux:event/on_tick
function #animated_java:tux/as_root/post_tick